name: i18n

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install gettext
      run: sudo apt-get -y install gettext
      
    - name: create .pot
      run: pygettext -d autobrightness -o autobrightness/locales/autobrightness.pot autobrightness
      
    - name: remove POT-Creation-Date
      run: sed -i '/POT-Creation-Date/d' autobrightness/locales/autobrightness.pot
      
    - name: create .mo
      run: find autobrightness/locales/ -name \*.po -execdir msgfmt autobrightness.po -o autobrightness.mo \;
      
    - name: commit
      run: |
        git config --global user.name 'i18n Bot'
        git config --global user.email github-actions@users.noreply.github.com
        git add -A
        git commit -m 'Auto generate .pot and .mo files'
        git push
