name: autobrightness-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create .deb
      run: |
        dpkg-deb --build autobrightness-0.1.0
