name: autobrightness-CICD

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create .deb
      run: ./createdeb.sh 1
    - uses: actions/upload-artifact@master
      name: Upload Artifact
      with:
        name: deb
        path: autobrightness*.deb
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        name: Download Artifact
        with:
          name: deb
      - shell: bash
        run: ls
      - name: Upload
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: deb/autobrightness*.deb
