name: autobrightness-CICD

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create .deb
      run: ./createdeb.sh 1
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: autobrightness*.deb
