name: autobrightness-CICD

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Version name
      run: echo ::set-env name=VER::${GITHUB_REF#refs/*/}
    - name: Create .deb
      run: ./createdeb.sh "$VER"
      
    - uses: actions/upload-artifact@master
      name: Upload Artifact
      with:
        name: deb
        path: autobrightness*.deb
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        name: Download Artifact
      
      - uses: skx/github-action-publish-binaries@master
        name: Upload .deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: deb/autobrightness*.deb
