name: release

on:
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Version name
      run: echo ::set-env name=VER::${GITHUB_REF#refs/*/}
    - name: Create .deb
      run: ./createdeb.sh "$VER"
    - name: Create standalone binary
      run: |
        pip3 install wheel
        pip3 install setuptools
        pip3 install pyinstaller
        /home/runner/.local/bin/pyinstaller --windowed --onefile --name autobrightness autobrightness/__main__.py
        zip --junk-paths autobrightness_$VER-standalone.zip dist/autobrightness README.md
      
    - uses: actions/upload-artifact@master
      name: Upload deb artifact
      with:
        name: deb
        path: autobrightness*.deb
    - uses: actions/upload-artifact@master
      name: Upload standalone artifact
      with:
        name: standalone
        path: autobrightness*-standalone.zip
  
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Create exe
      run: |
        pip install pyinstaller
        pyinstaller --windowed --onefile --name autobrightness autobrightness/__main__.py
        Compress-Archive -Path dist\autobrightness.exe,README.md -DestinationPath autobrightness_${GITHUB_REF#refs/*/}-windows.zip
      
    - uses: actions/upload-artifact@master
      name: Upload exe artifact
      with:
        name: exe
        path: autobrightness*-windows.zip
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Create macos app
      run: |
        pip3 install pyinstaller
        pyinstaller --windowed --onefile --name autobrightness autobrightness/__main__.py
        zip --recurse-paths autobrightness_${GITHUB_REF#refs/*/}-macos.zip dist README.md
      
    - uses: actions/upload-artifact@master
      name: Upload macos artifact
      with:
        name: macos
        path: autobrightness*-macos.zip
  
  publish:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        name: Download Artifacts
      
      - uses: skx/github-action-publish-binaries@master
        name: Upload .deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: deb/autobrightness*.deb

      - uses: skx/github-action-publish-binaries@master
        name: Upload standalone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: standalone/autobrightness*-standalone.zip

      - uses: skx/github-action-publish-binaries@master
        name: Upload exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: exe/autobrightness*-windows.zip
      
      - uses: skx/github-action-publish-binaries@master
        name: Upload mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: mac/autobrightness*-mac.zip
