name: SonarCloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  coverage:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install .
    
    - name: run coverage
      run: |
        coverage run --source . -m unittest discover -s tests
        coverage xml
    
    - name: Upload coverage.xml
      uses: actions/upload-artifact@master
      with:
        name: coverage
        path: coverage.xml
      
  sonar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@master
      name: Download Artifacts

    - uses: SonarSource/sonarcloud-github-action@master
      name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
